const COUNTRY_LIST = Object.freeze([
  'Australia',
  'Bangladesh',
  'Brazil',
  'Canada',
  'China',
  'Ethiopia',
  'France',
  'Germany',
  'Ghana',
  'India',
  'Indonesia',
  'Japan',
  'Kazakhstan',
  'Malaysia',
  'Mexico',
  'Mongolia',
  'Myanmar',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Pakistan',
  'Russia',
  'South Korea',
  'Spain',
  'Taiwan',
  'Thailand',
  'United Kingdom',
  'United States',
  'Uzbekistan',
  'Vietnam',
]);

const UNIVERSITY_LIST = Object.freeze([
  'ChungAng University',
  'Dongguk University',
  'Ewha Womans University',
  'Hanyang University',
  'Hankuk University of Foreign Studies',
  'Inha University',
  'Korea University',
  'Konkuk University',
  'KyungHee University',
  'Seoul City University',
  'Seoul National University',
  'Sogang University',
  'Sungkyunkwan University',
  "Sookmyung Women's University",
  'Yonsei University',
  'Oxford University',
  'Stanford University',
  'Massachusetts Institute of Technology',
  'Harvard University',
  'Cambridge University',
  'Princeton University',
  'California Institute of Technology',
  'Imperial College London',
  'University of California, Berkeley',
  'Yale University',
  'Swiss Federal Institute of Technology',
  'Tsinghua University',
  'University of Chicago',
  'Peking University',
  'Johns Hopkins University',
]);

export { COUNTRY_LIST, UNIVERSITY_LIST };
